### ISSUE TITLE
Where does the method get_element_by_attribute come from?

### ISSUE THREAD

**Issue by westonganger** [HellRok/TaylorPlayground#1]
I see the usage of a method `get_element_by_attribute` to interact with the browser. Where does this come from? 

https://github.com/HellRok/TaylorPlayground/blob/708af19d7aa38a27db082fd6625e456bb5aab495/game.rb#L7

If I try to use this method in my own taylor app I get

```
undefined method 'get_attribute_from_element' (NoMethodError)
```

**Comment by westonganger** [comment]
Ok I found the docs for this, https://taylor.oequacki.com/documentation/taylor/latest/top-level-namespace.html#get_attribute_from_element-instance_method

Guess I can dig in more on my issues for undefined method

**Comment by HellRok** [comment]
That interesting, can you post a snippet of your code trying to use it if you're still having issues.

**Comment by westonganger** [comment]
Steps to reproduce, use a web-only method such as `get_element_by_attribute` then launching using `taylor` (or `taylor run` since run is the default) then you will receive the exception. If you use `taylor export` then you no longer receive the exception. 

Ideas for improvement

- Maybe for apps targeting only web then `taylor run` could be disabled with a helpful error message
- Maybe platform specific methods could provide a more helpful error message rather than NoMethodError

**Comment by HellRok** [comment]
I really liked your idea where it would raise a more specific error, so I've implemented that and it will be released in the next version of Taylor.

Instead of getting a `NoMethodError` you will now get a `PlatformSpecificMethodCalledOnWrongPlatformError` error with a helpful message like `set_main_loop is only available for Web exports`
